"use client";

import { useForm } from "@tanstack/react-form";
import { FcGoogle } from "react-icons/fc";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

import {
  Field,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";

import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { uploadPhoto } from "@/lib/uploadPhoto";

export function RegistrationPage({ trigger, open, onOpenChange }) {
  const form = useForm({
    defaultValues: {
      name: "",
      email: "",
      photo: null,
      password: "",
      role: "tenant",
    },

    onSubmit: async ({ value }) => {
      try {
        console.log("Registration data:", value);

        // Temporary ID for the uploaded user's folder.
        // Ideally use the ID generated by your backend/database.
        const userId = crypto.randomUUID();

        let photoUrl = "";

        // Upload image to Supabase
        if (value.photo instanceof File) {
          photoUrl = await uploadPhoto(value.photo, userId);
        }

        console.log("Supabase photo URL:", photoUrl);

        // Send registration data + image URL to your backend
        // const response = await fetch("/api/register", {
        //   method: "POST",
        //   headers: {
        //     "Content-Type": "application/json",
        //   },
        //   body: JSON.stringify({
        //     name: value.name.trim(),
        //     email: value.email.trim(),
        //     password: value.password,
        //     role: value.role,
        //     photoUrl,
        //   }),
        // });

        // const data = await response.json();

        // if (!response.ok) {
        //   throw new Error(data.message || "Registration failed");
        // }

        // console.log("Registration successful:", data);

        form.reset();

        onOpenChange?.(false);
      } catch (error) {
        console.error("Registration failed:", error);

        // You can later connect this to a form-level error state/toast.
        alert(error.message);
      }
    },
  });

  const handleGoogleSignin = () => {
    console.log("Google sign in clicked");
  };

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      {trigger && <SheetTrigger render={trigger} />}

      <SheetContent className="overflow-y-auto">
        <SheetHeader>
          <SheetTitle>Registration</SheetTitle>

          <SheetDescription>
            Create your account to book properties and view property details.
          </SheetDescription>
        </SheetHeader>

        <form
          onSubmit={(event) => {
            event.preventDefault();
            event.stopPropagation();

            form.handleSubmit();
          }}
          className="flex flex-col gap-6 px-4 pb-6"
        >
          <FieldGroup>
            {/* ==================== NAME ==================== */}

            <form.Field
              name="name"
              validators={{
                onChange: ({ value }) => {
                  if (!value.trim()) {
                    return "Name is required";
                  }

                  if (value.trim().length < 2) {
                    return "Name must be at least 2 characters";
                  }

                  return undefined;
                },

                onBlur: ({ value }) => {
                  if (!value.trim()) {
                    return "Name is required";
                  }

                  return undefined;
                },
              }}
            >
              {(field) => {
                const isInvalid =
                  field.state.meta.isTouched && !field.state.meta.isValid;

                return (
                  <Field data-invalid={isInvalid}>
                    <FieldLabel htmlFor={field.name}>Full Name</FieldLabel>

                    <Input
                      id={field.name}
                      name={field.name}
                      value={field.state.value}
                      onBlur={field.handleBlur}
                      onChange={(event) =>
                        field.handleChange(event.target.value)
                      }
                      aria-invalid={isInvalid}
                      placeholder="John Doe"
                      autoComplete="name"
                    />

                    <FieldDescription>Enter your full name.</FieldDescription>

                    {isInvalid && (
                      <FieldError errors={field.state.meta.errors} />
                    )}
                  </Field>
                );
              }}
            </form.Field>

            {/* ==================== EMAIL ==================== */}

            <form.Field
              name="email"
              validators={{
                onChange: ({ value }) => {
                  if (!value.trim()) {
                    return "Email is required";
                  }

                  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

                  if (!emailRegex.test(value.trim())) {
                    return "Please enter a valid email address";
                  }

                  return undefined;
                },

                onBlur: ({ value }) => {
                  if (!value.trim()) {
                    return "Email is required";
                  }

                  return undefined;
                },
              }}
            >
              {(field) => {
                const isInvalid =
                  field.state.meta.isTouched && !field.state.meta.isValid;

                return (
                  <Field data-invalid={isInvalid}>
                    <FieldLabel htmlFor={field.name}>Email</FieldLabel>

                    <Input
                      id={field.name}
                      name={field.name}
                      type="email"
                      value={field.state.value}
                      onBlur={field.handleBlur}
                      onChange={(event) =>
                        field.handleChange(event.target.value)
                      }
                      aria-invalid={isInvalid}
                      placeholder="john@example.com"
                      autoComplete="email"
                    />

                    <FieldDescription>
                      We&apos;ll use this email to access your account.
                    </FieldDescription>

                    {isInvalid && (
                      <FieldError errors={field.state.meta.errors} />
                    )}
                  </Field>
                );
              }}
            </form.Field>

            {/* ==================== PHOTO ==================== */}

            <form.Field
              name="photo"
              validators={{
                onChange: ({ value }) => {
                  if (!value) {
                    return "Profile photo is required";
                  }

                  if (!(value instanceof File)) {
                    return "Please select a valid image";
                  }

                  const allowedTypes = [
                    "image/jpeg",
                    "image/png",
                    "image/webp",
                  ];

                  if (!allowedTypes.includes(value.type)) {
                    return "Only JPG, PNG, and WebP images are allowed";
                  }

                  const maxSize = 5 * 1024 * 1024;

                  if (value.size > maxSize) {
                    return "Image must be smaller than 5MB";
                  }

                  return undefined;
                },
              }}
            >
              {(field) => {
                const isInvalid =
                  field.state.meta.isTouched && !field.state.meta.isValid;

                return (
                  <Field data-invalid={isInvalid}>
                    <FieldLabel htmlFor={field.name}>Profile Photo</FieldLabel>

                    <Input
                      id={field.name}
                      name={field.name}
                      type="file"
                      accept="image/jpeg,image/png,image/webp"
                      onBlur={field.handleBlur}
                      onChange={(event) => {
                        const file = event.target.files?.[0] ?? null;

                        field.handleChange(file);
                      }}
                      aria-invalid={isInvalid}
                    />

                    <FieldDescription>
                      JPG, PNG, or WebP. Maximum size 5MB.
                    </FieldDescription>

                    {isInvalid && (
                      <FieldError errors={field.state.meta.errors} />
                    )}
                  </Field>
                );
              }}
            </form.Field>

            {/* ==================== PASSWORD ==================== */}

            <form.Field
              name="password"
              validators={{
                onChange: ({ value }) => {
                  if (!value) {
                    return "Password is required";
                  }

                  if (value.length < 8) {
                    return "Password must be at least 8 characters";
                  }

                  if (!/[A-Z]/.test(value)) {
                    return "Password must contain an uppercase letter";
                  }

                  if (!/[a-z]/.test(value)) {
                    return "Password must contain a lowercase letter";
                  }

                  if (!/[0-9]/.test(value)) {
                    return "Password must contain a number";
                  }

                  return undefined;
                },

                onBlur: ({ value }) => {
                  if (!value) {
                    return "Password is required";
                  }

                  return undefined;
                },
              }}
            >
              {(field) => {
                const isInvalid =
                  field.state.meta.isTouched && !field.state.meta.isValid;

                return (
                  <Field data-invalid={isInvalid}>
                    <FieldLabel htmlFor={field.name}>Password</FieldLabel>

                    <Input
                      id={field.name}
                      name={field.name}
                      type="password"
                      value={field.state.value}
                      onBlur={field.handleBlur}
                      onChange={(event) =>
                        field.handleChange(event.target.value)
                      }
                      aria-invalid={isInvalid}
                      placeholder="••••••••"
                      autoComplete="new-password"
                    />

                    <FieldDescription>
                      Minimum 8 characters with uppercase, lowercase, and a
                      number.
                    </FieldDescription>

                    {isInvalid && (
                      <FieldError errors={field.state.meta.errors} />
                    )}
                  </Field>
                );
              }}
            </form.Field>
          </FieldGroup>

          {/* ==================== ACTIONS ==================== */}

          <SheetFooter className="px-0">
            <Button type="submit" className="w-full">
              Create Account
            </Button>

            <Button
              type="button"
              variant="outline"
              className="w-full"
              onClick={handleGoogleSignin}
            >
              <FcGoogle />
              <span>Sign in with Google</span>
            </Button>

            <Button
              type="button"
              variant="outline"
              className="w-full"
              onClick={() => onOpenChange?.(false)}
            >
              Cancel
            </Button>
          </SheetFooter>
        </form>
      </SheetContent>
    </Sheet>
  );
}
